version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres
    env_file:
      - .env.development.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fbsr_net
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    env_file:
      - .env.development.local
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - fbsr_net
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    env_file:
      - .env.development.local
    ports:
      - "3000:3000"
    networks:
      - fbsr_net
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin.dev
    env_file:
      - .env.development.local
    ports:
      - "3001:3000"
    networks:
      - fbsr_net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  fbsr_net:
    driver: bridge
